<?php

return [
    'name' => 'General',

    'region' => [
        /** \libphonenumber\ShortNumbersRegionCodeSet::SHORT_NUMBERS_REGION_CODE_SET */
        'country' => env('APP_COUNTRY', 'IR'),

        'countries' => [
            'IR' => [
                'id' => 103,
                'name' => 'Iran',
                'iso3' => 'IRN',
                'iso2' => 'IR',
                'numeric_code' => '364',
                'phone_code' => '98',
                'capital' => 'Tehran',
                'capital_city_id' => 1,
                'currency' => 'IRR',
                'currency_name' => 'Iranian rial',
                'currency_symbol' => 'IRR',
                'tld' => '.ir',
                'native' => 'ایران',
                'languages' => 'Iranian, Persian',
                'locale' => 'fa_IR',
                'timezones' => [
                    [
                        'tzName' => 'Iran Daylight Time',
                        'zoneName' => 'Asia/Tehran',
                        'gmtOffset' => 12600,
                        'abbreviation' => 'IRDT',
                        'gmtOffsetName' => 'UTC+03:30',
                    ],
                ],
                'translations' => [
                    'de' => 'Iran', 'es' => 'Iran', 'fa' => 'ایران', 'fr' => 'Iran',
                    'hr' => 'Iran', 'ja' => 'イラン・イスラム共和国', 'ko' => '이란',
                    'nl' => 'Iran', 'pl' => 'Iran', 'pt' => 'Irão', 'ru' => 'Иран',
                    'tr' => 'İran', 'uk' => 'Іран', 'pt-BR' => 'Irã', 'zh-CN' => '伊朗',
                ],
                'latitude' => '32.00000000',
                'longitude' => '53.00000000',
                'emoji' => '🇮🇷',
                'emojiU' => 'U+1F1EE U+1F1F7',
            ],
            'AE' => [
                'id' => 231,
                'name' => 'United Arab Emirates',
                'iso3' => 'ARE',
                'iso2' => 'AE',
                'numeric_code' => '784',
                'phone_code' => '971',
                'capital' => 'Abu Dhabi',
                'capital_city_id' => null,
                'currency' => 'AED',
                'currency_name' => 'United Arab Emirates dirham',
                'currency_symbol' => 'إ.د',
                'tld' => '.ae',
                'native' => 'دولة الإمارات العربية المتحدة',
                'languages' => 'Emirati, Emirian, Emiri',
                'locale' => 'fa_IR',
                'timezones' => [
                    [
                        'tzName' => 'Gulf Standard Time',
                        'zoneName' => 'Asia/Dubai',
                        'gmtOffset' => 14400,
                        'abbreviation' => 'GST',
                        'gmtOffsetName' => 'UTC+04:00',
                    ],
                ],
                'translations' => [
                    'de' => 'Vereinigte Arabische Emirate', 'es' => 'Emiratos Árabes Unidos',
                    'fa' => 'امارات متحده عربی', 'fr' => 'Émirats arabes unis', 'hr' => 'Ujedinjeni Arapski Emirati',
                    'it' => 'Emirati Arabi Uniti', 'ja' => 'アラブ首長国連邦', 'ko' => '아랍에미리트',
                    'nl' => 'Verenigde Arabische Emiraten', 'pl' => 'Zjednoczone Emiraty Arabskie',
                    'pt' => 'Emirados árabes Unidos', 'ru' => 'Объединенные Арабские Эмираты',
                    'tr' => 'Birleşik Arap Emirlikleri', 'uk' => "Об''єднані Арабські Емірати",
                    'pt-BR' => 'Emirados árabes Unidos', 'zh-CN' => '阿拉伯联合酋长国',
                ],
                'latitude' => '24.00000000',
                'longitude' => '54.00000000',
                'emoji' => '🇦🇪',
                'emojiU' => 'U+1F1E6 U+1F1EA',
            ],
            'HU' => [
                'id' => 99,
                'name' => 'Hungary',
                'iso3' => 'HUN',
                'iso2' => 'HU',
                'numeric_code' => '348',
                'phone_code' => '36',
                'capital' => 'Budapest',
                'capital_city_id' => 5001,
                'currency' => 'HUF',
                'currency_name' => 'Hungarian forint',
                'currency_symbol' => 'Ft',
                'tld' => '.hu',
                'native' => 'Magyarország',
                'languages' => 'Hungarian, Magyar',
                'locale' => 'fa_IR',
                'timezones' => [
                    [
                        'tzName' => 'Central European Time',
                        'zoneName' => 'Europe/Budapest',
                        'gmtOffset' => 3600,
                        'abbreviation' => 'CET',
                        'gmtOffsetName' => 'UTC+01:00',
                    ],
                ],
                'translations' => [
                    'de' => 'Ungarn', 'es' => 'Hungría', 'fa' => 'مجارستان', 'fr' => 'Hongrie',
                    'hr' => 'Mađarska', 'it' => 'Ungheria', 'ja' => 'ハンガリー', 'ko' => '헝가리',
                    'nl' => 'Hongarije', 'pl' => 'Węgry', 'pt' => 'Hungria', 'ru' => 'Венгрия',
                    'tr' => 'Macaristan', 'uk' => 'Угорщина', 'pt-BR' => 'Hungria', 'zh-CN' => '匈牙利',
                ],
                'latitude' => '47.00000000',
                'longitude' => '20.00000000',
                'emoji' => '🇭🇺',
                'emojiU' => 'U+1F1ED U+1F1FA',
            ],
        ],
    ],
];
